# Generated by Django 2.2.6 on 2019-10-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100)),
                ('mdate', models.DateTimeField()),
                ('mhero', models.CharField(help_text='add Hero/Actress name', max_length=50)),
            ],
        ),
    ]
