# Generated by Django 2.2.6 on 2019-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='mdate',
            field=models.IntegerField(),
        ),
    ]
