# Generated by Django 2.2.6 on 2019-10-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_auto_20191014_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='mhero',
            new_name='Actor',
        ),
        migrations.RenameField(
            model_name='movieinfo',
            old_name='mname',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='movieinfo',
            old_name='mdate',
            new_name='Release_Year',
        ),
    ]
